"""Add unit_price to Equipment model

Revision ID: 08914ae9234a
Revises: 1265d34eb682
Create Date: 2024-10-20 20:13:02.064445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08914ae9234a'
down_revision = '1265d34eb682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
