"""Add description to projects

Revision ID: 1265d34eb682
Revises: 
Create Date: 2024-10-20 19:59:55.213048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1265d34eb682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
